language: ruby
cache: bundler
script: bundle exec rails test

services:
  - postgresql

before_install:
  - nvm install node
  - npm i -g yarn
  - yarn
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
  - secure: BjpyYj5yEqARg8ozd0MEh3uupFXEThcOz4vSszjqVQaMIBlcoj8zmFe8uTM484ZwJukMBAsahsG+Vwu1BZ2HSlH8G5Dzs5HbpLGASoqt3Zi9+1t72vUY4qRMXLMmW8na/1Z0RpcmyxPrhBHkorAHDnSCek5ZerRzRjPN6IMzF7lVkOFEahaBlLVEJmDSqQtrlQ/exkZ//nMg32WxbbyzO0ejfu/wh8QYxiu06Sts/mq9JuwEA7s1mIKHpuQSjzqi4b5ZOOfKP5n7sFdEmB6AgORGPBp+uzPrLSerN8Je0Zzp4WOiSDXYDV7JFY1kCOfSJlp1jcyqhOzI9UIaJRgq/fN4UQrwCDpvjIO60gEpsGGsAFtjnRtSKlMakRxmruScEEfCtbjVsm+hQTFrx1qzMHP7Rz/HivWePxeNpNSszQA59N4zagv1YUHnrJpBUUSnqVnB4is/mXTlpKN/LT3Zf1Wm2se9uNssGKfyDbAWaCzngTGGWaEXqyirvs4csUXB1I33oRLMfx2VrMKaNA5VPHNaEVcZAm5XojkRwNa+qVePbiqc36e88emR+i4P9TAKNrocON4XnNYmFnIBzl0aqsbxBzU7PpaDQeamQ0Km1X37S9rZIil0zk0ERMFp5JsJGh7dYSpICrKkyV2+gsjw7Tr+n0t20sSoh68zph3g76I=
  - secure: lwjWiNaWVzmFXKJfZYPbCyKbRS0tlPxD2Iuc7oJ1bRIHjj6vAyuQyt6YH8jy2rEU1qLt+n+qfeYiwRyFfFjKz7A6q18Chz3QHI1TUu4vGZuOvqC+oM6FKDx68bnfB33B42VIkmul32Vi48zTrpnYCpvJMuPCys+JQlqcjy5wSSNDKhtNELfDouQShFzkMl/uK5AVTF/aBLz8XKhjdTBMUUcNVPgCdzxxeMuyBd02IaOgorzCLbswVq+B2L7VXGU+fo/cDjaaKzKHhR3yeTV/Q+BQNV6H51a5CD/w3/ojKuJgZV6DteCS8XuUfudvzFoA3cdsou2R9NnkOGwDfZ8xUNvdzLumdEAVfUrU/gxz57L6nuTZKA4NOIUmvDJ5LtcvlLKfxAA4DBf1p5ka+TdBuEFX3LSHxluP5PgghJk0XOrr7oNWrhT0qoYk7i/fQChpU5VAgWSK99tChD+9XwqC5OhzXTRGgRw0ktYPRhc0kTNghSFu4JIfbMjWFQMJUVGKBxbeR5EeUZdTgutTinJiRIrIrflLevAS7hva4BaEvzCxQ4fPPZjymnrSaZ9wvEvo8oQgOE/zZeEd8VPx8JIag1/bcOLrmidxrB9PeZXts+CEE4CbS6x2RPyOBkej0zv70PdjtHljvXaPMFsPBXEOJXz58PDRQTckgzqQvW82Tt8=
